/* Autogenerated file. Do not edit manually. */
/* tslint:disable */

export { CertChainFactory__factory } from "./CertChainFactory__factory";
export { CertChainRegistry__factory } from "./CertChainRegistry__factory";
