/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface CertChainFactoryInterface extends Interface {
  getFunction(
    nameOrSignature: "issueCertificate" | "registry"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "CertificateMinted"): EventFragment;

  encodeFunctionData(
    functionFragment: "issueCertificate",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "issueCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
}

export namespace CertificateMintedEvent {
  export type InputTuple = [
    institution: AddressLike,
    instructor: AddressLike,
    ipfsHash: string
  ];
  export type OutputTuple = [
    institution: string,
    instructor: string,
    ipfsHash: string
  ];
  export interface OutputObject {
    institution: string;
    instructor: string;
    ipfsHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CertChainFactory extends BaseContract {
  connect(runner?: ContractRunner | null): CertChainFactory;
  waitForDeployment(): Promise<this>;

  interface: CertChainFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  issueCertificate: TypedContractMethod<
    [arg0: string, arg1: AddressLike],
    [void],
    "view"
  >;

  registry: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "issueCertificate"
  ): TypedContractMethod<[arg0: string, arg1: AddressLike], [void], "view">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "CertificateMinted"
  ): TypedContractEvent<
    CertificateMintedEvent.InputTuple,
    CertificateMintedEvent.OutputTuple,
    CertificateMintedEvent.OutputObject
  >;

  filters: {
    "CertificateMinted(address,address,string)": TypedContractEvent<
      CertificateMintedEvent.InputTuple,
      CertificateMintedEvent.OutputTuple,
      CertificateMintedEvent.OutputObject
    >;
    CertificateMinted: TypedContractEvent<
      CertificateMintedEvent.InputTuple,
      CertificateMintedEvent.OutputTuple,
      CertificateMintedEvent.OutputObject
    >;
  };
}
